repos:
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        # No args here; Black will read pyproject.toml
        exclude: |
          (?x)^(
            data/|
            web/downloads/|
            snapshot/|
            .*\.ipynb_checkpoints/
          )

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.4
    hooks:
      - id: ruff
        args: ["--fix"]
        exclude: |
          (?x)^(
            data/|
            web/downloads/|
            snapshot/|
            .*\.ipynb_checkpoints/
          )